### ISSUE TITLE
changes for version 1 release

### ISSUE THREAD

**Issue by audiracmichelle** [NSAPH-Data-Processing/zip_fips_master_xwalk#15]
[ ] snakemake is not indentifying the requirement of expanded files here
[ ] might remove run_xwalk_pipeline.sh in favor of snakemake
[ ] remove path in rmd, rmd files usually run from notebook location

**Comment by audiracmichelle** [comment]
in snakemake the master xwalk quarter is fixed to the default=4

**Comment by audiracmichelle** [comment]
all quarters are downloaded in the snakemake

**Comment by audiracmichelle** [comment]
intermediate steps incorporates all quarters

**Comment by audiracmichelle** [comment]
rmd can pull the all quarters data from the intermediate step

**Comment by audiracmichelle** [comment]
@jckitch let me know if you have questions about the listed changes for release v1!

**Comment by jckitch** [comment]
I like the changes! Nice work @audiracmichelle
